### ISSUE TITLE
Project To-Do List

### ISSUE THREAD

**Issue by Megaf** [FlightGearRepublic/FG-1000#1]
# TO-DO LIST

## 3D Model
General 3D model and design of the fighter/

- [ ] Create 3D Model - https://github.com/FlightGearRepublic/FG-1000/issues/3
- [ ] Undercarriage - https://github.com/FlightGearRepublic/FG-1000/issues/4
- [ ] Cockpit - https://github.com/FlightGearRepublic/FG-1000/issues/5

## Avionics
Radar, RWR, MFD.

- [ ] MFD, Radar and RWR - https://github.com/FlightGearRepublic/FG-1000/issues/6
- [ ] Weapons - https://github.com/FlightGearRepublic/FG-1000/issues/8
- [ ] DataLink and IFF - https://github.com/FlightGearRepublic/FG-1000/issues/7

## Systems
Electrics, Hydraulics, Pneumatics, Electronics.

- [ ] Define a clear PropertyList structure for everything. Using FlightGear defaults when possible.
- [ ] Implement Electrics
- [ ] Implement Hydraulics
- [ ] Implement Pneumatics
- [ ] Implement Electronics

## Weapons
Implementation of missiles and damage.

- [ ] Weapons - https://github.com/FlightGearRepublic/FG-1000/issues/8

## FDM
Aerodynamics, Engine, FBW,

- [ ] Implement Engine - https://github.com/FlightGearRepublic/FG-1000/issues/10
- [ ] Run engine data and aeroplane dimensions in Aeromatic to get basic FDM
- [ ] Make OpenVSP model
- [ ] Fine tune JSBSim FDM tables from OpenVSP

## Repository Information
Things to do in the repository

- [x] Update repository social image to reflect new name.

**Comment by valtsu41** [comment]
Now everything is in a single issue card on the project board.
