### ISSUE TITLE
[TODO] - 3D Model - Undercarriage

### ISSUE THREAD

**Issue by Megaf** [FlightGearRepublic/FG-1000#4]
# Undercarriage

- [ ] Define which undercarriage we are going to use.
- [ ] Model the landing gear
- [ ] Add the landing gear to the fuselage
- [ ] Make stealth landing gear doors in the fuselage
- [ ] Animate landing gear
