### ISSUE TITLE
[TODO] - Cockpit

### ISSUE THREAD

**Issue by Megaf** [FlightGearRepublic/FG-1000#5]
# Cockpit

- [ ] Define cockpit layout
- [ ] Model cockpit 3D model
- [ ] Add flight controls and instruments
