### ISSUE TITLE
[TODO] - Weapons

### ISSUE THREAD

**Issue by Megaf** [FlightGearRepublic/FG-1000#8]
# Weapons

- [ ] Decide on which weapons we will have
- [ ] Implement weapons targeting and firing
- [x] Implement receiving damage
- [ ] Implement inflicting damage
