### ISSUE TITLE
[TODO] - Project renaming.

### ISSUE THREAD

**Issue by Megaf** [FlightGearRepublic/FG-1000#9]
Rename whole project from MF-1000 to FG-1000.

- [x] Change repository name.
- [x] Change name in description
- [x] Change name on Readme
- [x] Change name on social image
- [x] File names and file's content.

**Comment by Megaf** [comment]
Fixed.

**Comment by Megaf** [comment]
Still need to rename the -set file and fdm file.
And change the description.
